name: warzone_api
description: Unofficial API for Call of Duty Warzone, this plugin does not guarantee 100% functionality, as it may change.
version: 1.0.13
homepage: https://github.com/DomingoMG/WarzoneApi

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
